author: yude
author_title: 特に何も行っていない
avatar: https://avatars.githubusercontent.com/yudete

url: https://blog.yude.moe

widgets:
  - search
  - recent_posts
  - archive

contact:
  url: https://twitter.com/yudete
  icon: twitter

disqus_shortname: yudelog

sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml