title: yude's blog
subtitle: null
description: yude のブログです。 備忘録等を掲載しています。
keywords: 'yude, yudelog, ゆで, yudete'
author: yude
language: ja
timezone: Japan
url: 'https://blog.yude.jp'
root: /
permalink: ':title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: admin/config.yml
new_post_name: ':title.md'
default_layout: post
titlecase: false
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY/MM/DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: apollo
disqus_shortname: yudelog
prism_plus:
  enable: true
  vendors:
    base_url: 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/'
    prism:
      - prism.min.js
      - plugins/line-numbers/prism-line-numbers.min.js
      - components/prism-bash.min.js
      - components/prism-json.min.js
      - components/prism-php.min.js
      - components/prism-python.min.js
    prism_css:
      - themes/prism-twilight.min.css
      - plugins/line-numbers/prism-line-numbers.min.css
sitemap:
  path: sitemap.xml
deploy:
  type: git
  repo: 'git@github.com:yudete/blog.git'
  branch: master
