bootswatch: lumen

slogan: ""

menu:
  - title: アーカイブ
    url: archives
    intro: "記事一覧 / Archives"
    icon: "fa fa-archive"
  - title: カテゴリー
    url: categories
    intro: "カテゴリー一覧 / Categories"
    icon: "fa fa-folder"
  - title: タグ
    url: tags
    intro: "タグ一覧 / Tag Listing"
    icon: "fa fa-tags"

links:
  - title: Twitter
    url: https://twitter.com/yudete
    intro: "Twitter @yudete"
    icon: "fa fa-twitter"

widgets:
- search
- category
- tagcloud
- recent_posts
- links
- sponsor

rss: true
fancybox: true
favicon: favicon.png
google_analytics:
