backend:
  name: github
  repo: yudecchi/blog
  branch: master

media_folder: source/images/

collections:
- name: "blog" # Used in routes, e.g. /admin/collections/blog
  label: "ブログ" # Used in the UI
  folder: "source/_posts" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "タイトル", name: "title", widget: "string"}
    - {label: "公開日時", name: "date", widget: "datetime", default: ""}
    - {label: "カテゴリー", name: "categories", widget: "list", default: ""}
    - {label: "著者", name: "author", widget: "string", default: "yude"}
    - {label: "本文", name: "body", widget: "markdown"}
    - {label: "レイアウト", name: "layout", widget: "hidden", default: "blog"}
  meta:
    - {label: "タグ", name: "tags", widget: "list", default: "" }
