name: Hexo Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - uses: yrpang/github-actions-hexo@v1.3
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: PUBLISHER_USER_NAME
          email: PUBLISHER_EMAIL_ADDRESS