name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          email: ${{ secrets.CF_EMAIL }}
          workingDirectory: './public'